### ISSUE TITLE
Poisson's Solver

### ISSUE THREAD

**Issue by adityarn** [adityarn/PythonWorkshopIITM_LUG#2]
Why is the C++ code taking ~ 21s, while Numpy/Numba/Cython codes take only ~6s??

**Comment by srinix07** [comment]
C++ poisson code takes more time because the vector 'array'  is non contiguous.

` vector <vector <double> > array; `

 This is a big deal when using memory access in nested loops.
The proper way to allocate 2D arrays contiguously (as it is usually done in C and Fortran and hence in numpy) is to unroll 2D to 1D and allocate memory.

C++:
`  double *array = new double[n * n]; `
 C:
` double *array = malloc(n * n * sizeof(double))`

Accessing 'array':
`array[n * i + j] = (array[n * i + j+1] + array[n * i + j-1] + array[ n *( i+1) + j] + array[n*(i-1) + j]) * 0.25;`

Freeing 'array':
C++;
`delete [] array;`

C:
`free(array);`

I have made a C code and benchmarked it. I have created a Pull request for the extra files.

**Comment by adityarn** [comment]
Great! Also, I added you as a collaborator, that should let you upload/merge etc right?

Does the Numpy tutorial seem ready to be finalised?
